name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  build-KB-Index:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build KB Index
        shell: pwsh
        run: | 
          ./scripts/rebuild-kb-index.ps1
      - uses: stefanzweifel/git-auto-commit-action@v5
      - name: Get Latest Commit SHA
        id: get-commit-sha
        run: echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
  deploy:
    runs-on: ubuntu-latest
    needs: build-KB-Index
    steps:
      - name: Checkout updated repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all history is fetched
          ref: ${{ needs.build-KB-Index.outputs.commit_sha }} # Reference the updated commit
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox 
      - run: mkdocs gh-deploy --force